json.id profile.id
json.user_id profile.user_id
json.name profile.name
json.brokerage profile.brokerage
json.phone profile.phone
json.emailcontact profile.emailcontact
json.photo_url asset_path(profile.photo.url(:big))
json.created_at profile.created_at
json.updated_at profile.updated_at
